Document: dronekit-la
Title: Debian dronekit-la Manual
Author: <insert document author here>
Abstract: This manual describes what dronekit-la is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dronekit-la/dronekit-la.sgml.gz

Format: postscript
Files: /usr/share/doc/dronekit-la/dronekit-la.ps.gz

Format: text
Files: /usr/share/doc/dronekit-la/dronekit-la.text.gz

Format: HTML
Index: /usr/share/doc/dronekit-la/html/index.html
Files: /usr/share/doc/dronekit-la/html/*.html
